name: Build and Push Docker Images on Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push_on_push:
    name: Build and push the docker images to container registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PWD: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PWD
    
    - name: Build and push web-img
      run: |
        cd addons/gst-web
        docker build . --tag coredgeio/dstreamer-web-img:main
        docker push coredgeio/dstreamer-web-img:main
    
    - name: Build and push python-build
      run: |
        docker build . --tag coredgeio/dstreamer-python-build:main
        docker push coredgeio/dstreamer-python-build:main
    
    - name: Build and push dstreamer
      run: |
        cd docker-images/base/dstreamer
        docker build . --tag coredgeio/dstreamer:main
        docker push coredgeio/dstreamer:main
    
    - name: Build and push desktop
      run: |
        cd docker-images/base/desktop
        docker build . --tag coredgeio/dstreamer-desktop:main
        docker push coredgeio/dstreamer-desktop:main